### PR TITLE
Fix cli installation docs

### PR DESCRIPTION
**Pull request by rexposadas**
The `go get` command fails with the following error: 

% go get github.com/fyne-io/terminal/cmd/fyneterm
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
        
        
        
The way to install it is to use `go install`. This will put the binary in the GOBIN directory.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks for the PR. I would suggest that you read the discussion on https://github.com/fyne-io/fyne/pull/3155#discussion_r927020887. The `go install` command only works on Go 1.16 and up when using `@latest`.

**Comment by rexposadas** [comment]
Thanks @Jacalz ,  I didn't catch that. 

I made a comment in the discussion you linked.

**Comment by Jacalz** [comment]
Indeed. We need to separate mentions. Thanks for the comment on the other PR. It does unfortunately look like that one is a bit stuck at the moment.

**Review by andydotxyz — APPROVED** [review]
We now only support Go 1.17+ so this is ok

**Review by Jacalz — APPROVED** [review]

**Pull request merged**
