### PR TITLE
fix buffer cutoff mid escape

### PR DESCRIPTION
**Pull request by mgazza**
Fix issue when buffer cuts off mid escape sequence

### CODE REVIEW

**Comment by figuerom16** [comment]
I wonder if this fixes #70

**Comment by mgazza** [comment]
If you can reproduce 70 then it would be worth tee'ing the stdout to file so you can inspect it. Essentially I have a set of files which I cat to test the console. I noticed that colors were blinking after my most recent change and that is because the ESC state was [not continued between buffer processing](https://github.com/codelaboratory-bot/terminal/blob/master/output.go#L120-L120); so the state.code sort of got added to the previous code. If you undo my potential fix and run the test and inspect the diff of the terms content you will see what i mean.

**Comment by andydotxyz** [comment]
> I wonder if this fixes #70

Yes I wondered that too - I have to get back to the computer where I can replicate it. 
On my TODO list for tomorrow.

**Comment by andydotxyz** [comment]
> I wonder if this fixes #70

Sadly it doesn't

**Review by andydotxyz — APPROVED** [review]
Thanks for this

**Pull request merged**
