### PR TITLE
Implement new Style() method of TermGridStyle interface

### PR DESCRIPTION
**Pull request by mgazza**
required as per https://github.com/fyne-io/fyne/pull/4244

### CODE REVIEW

**Comment by mgazza** [comment]
Yep, I'll update this now its been merged

**Comment by andydotxyz** [comment]
Apologies for the failure - somehow a previous PR triggered a break that was not caught. I pushed a fix, so merging in latest develop should fix it.

**Comment by andydotxyz** [comment]
Oh my mistake - it was not a rebase that it needed, it was an update of the fyne dep in go.mod - I forgot which repository we are in sorry.

**Review by andydotxyz — APPROVED** [review]
Great, thanks for this :)

**Pull request merged**
