### PR TITLE
Added bare basic terminal example

### PR DESCRIPTION
**Pull request by rmasci**
For me, I just wanted to know the basics. What is the bare minimum someone would need to just display a terminal? So I looked at fyneterm and wrote this. I thought a super basic example would be a good place to start, lay a foundation, then move up to fyneterm.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Doesn't it seem like this should be documentation rather than a complete application package?

**Comment by rmasci** [comment]
You could document it, but having a real hands on working terminal that you
can 'go run' is what I was looking for when I first cloned the Fyne
Terminal. It shows the simplicity of Fyne, I mean where else can you have a
real working terminal in less than 35 lines of code? The fyneterm
application you have now shows it's not a toy, fyne terminal can scale.

I saw the Local Shell example in the README and it too shows the simplicity
but you can't copy / paste / run it. I wouldn't change the readme, it's
fine the way it is.

I had a few minutes to kill on a friday between meetings at work, it made
more sense of things for me and I thought it might help someone else -- so
I gave you a pull request.

**Comment by andydotxyz** [comment]
> I saw the Local Shell example in the README and it too shows the simplicity but you can't copy / paste / run it. I wouldn't change the readme, it's fine the way it is.

I guess the purpose of the README is to show how to use it as a Fyne widget in any app (i.e. drop it into the hello world example in place of the label).
I didn't think this repo needed a demonstration of how to launch a Fyne app, as you say the README does not really need that info.
As this PR is doing just that I'm not sure why it's needed - none of the other widgets have an example that shows how to put it into the content of a window.

That said I'm not against including it - perhaps someone else can give their perspective such as @mgazza, @Jacalz or @Bluebugs ?

**Comment by Bluebugs** [comment]
The benefit I see from going in such a direction is that the example will be tested as part of the CI. Maybe a better way to do this would be to integrate that as a Go example and make it part of the normal go docs too. I haven't looked at all at the documentation or CI of this package and only relied on the code to understand how it work, so I do not know if what I am asking is a lot of work and should be done in another PR or if it is a simple request and could be made an improvement of this PR.

**Comment by Jacalz** [comment]
I think having it as a Go example would be better. Like @andydotxyz said, I don't think having a specific app for this is the right way to go.

**Comment by andydotxyz** [comment]
As discussed above let's not merge this additional command.
Feel free to re-open as documentation or one of the suggestions in the thread.

**Pull request closed without merging**
