### PR TITLE
Fix enter/return key

### PR DESCRIPTION
**Pull request by mgazza**
Enter/return key should be passed as is, the kernel will interpet the correct sequence

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
Ah great thanks

**Comment by andydotxyz** [comment]
You'll need to merge in the latest master branch and fix the conflict before we can merge, sorry.

**Comment by Bluebugs** [comment]
This is not exactly correct as you can get a control character from the terminal stream that define the mapping. See https://github.com/borisfaure/terminology/blob/master/src/bin/keyin.c#L159 for reference.

**Comment by mgazza** [comment]
Yes if your in raw mode you will receive the unmapped characters.  If not the kernel will map them for you. This fix is for exactly that, when the program is in raw mode the program would not respond to the enter key without this.

**Comment by Bluebugs** [comment]
When connected for example to a Windows machine, you would need to send \r\n for the Return key. I don't mind having that addressed at a later time, but basically I think this will mean running terminal on a Windows machine might not work until addressed.

**Comment by mgazza** [comment]
I will give it on windows. My use case was actually terminal -> ssh -> cobol term

**Comment by andydotxyz** [comment]
Let's not break anything!
Do we need to understand a new control sequence to switch mode to know if it's truly raw or a different OS on the other side?

**Comment by andydotxyz** [comment]
Looking at it again isn't this switching based on windows on the client rather than on the other end? If so does this raw mode only apply when it's a Unix system?

**Comment by Bluebugs** [comment]
The original code was broken when remote connecting from a Unix to Windows or the other way around, but Windows on Windows was working.

An yes, there is a ctrl to handle for this : https://github.com/borisfaure/terminology/blob/master/src/bin/keyin.c#L159 and for an extensive list of ctrl sequence: http://ttssh2.sourceforge.jp/manual/en/about/ctrlseq.html

**Comment by mgazza** [comment]
I've been hunting though the PuTTY code to try and find some switch but I
can't find one. When I looked into this last the mode wasn't communicated
via an escape sequence it was purely done via the kernel.

**Comment by andydotxyz** [comment]
I think Bluebugs has a point - see the escape check at https://github.com/borisfaure/terminology/blob/86c8a965a03a63ed014c051b84c0995a1c772b0f/src/bin/termptyesc.c#L382

Also note that the static check is failing for this PR, please update to match our format.

**Comment by mgazza** [comment]
> I think Bluebugs has a point - see the escape check at https://github.com/borisfaure/terminology/blob/86c8a965a03a63ed014c051b84c0995a1c772b0f/src/bin/termptyesc.c#L382
> 
> Also note that the static check is failing for this PR, please update to match our format.

OK found it.
Screenshot_20230913_204708_Chrome

**Comment by mgazza** [comment]
Hey guys, having some trouble with this, can someone tell me the expected output based on this 
```sh
echo -n "\x1b[20hhello\rworld"
```

**Comment by andydotxyz** [comment]
I tried that command on terminology and I get a debug printout on stdout then the terminal does as you show.
Looks like that isn't parsing right...

**Comment by andydotxyz** [comment]
Yup you're missing the "?" - it should be "\e[?20hhello\rworld"

**Comment by mgazza** [comment]
> Yup you're missing the "?" - it should be "\e[?20hhello\rworld"

Haha. /Facepalm I spent about 30mins googling that to 🤣. I'll fix this Monday. 
For what it's worth I tried with? In xterm and it did exactly the same.

**Comment by andydotxyz** [comment]
Looks good to me thanks, how's it for @Bluebugs ?

**Review by Bluebugs — APPROVED** [review]
Lgtm

**Review by andydotxyz — APPROVED** [review]
Thanks for this

**Pull request merged**
