### PR TITLE
Fix/control keys

### PR DESCRIPTION
**Pull request by mgazza**
Control key handling was broken. FyneTerm sent invalid keys such as the NAK character for ALT+U for example.

Please review both commits individually so we can choose an implementation

### CODE REVIEW

**Comment by andydotxyz** [comment]
Neither of these implementations will allow Ctrl+5 (for example) - thought the first seems worse as it would re-write that key to be the lowest control key supported.

I know we have spoken online, but from this patch it is not clear exactly what is being fixed here, or why limiting control key shortcuts to a limited set is the solution?

**Comment by mgazza** [comment]
What's your expectation with ctrl+5 as right now as it stands in main it will write 245.

**Comment by mgazza** [comment]
Would it help if I first committed the tests with expected and failing tests in a separate PR. 

The reported issue was that you can't enter foreign characters from windows or mac ( using the alt+code )

**Comment by andydotxyz** [comment]
> What's your expectation with ctrl+5 as right now as it stands in main it will write 245.

I think that with current implementation:

* all control keys will be sent
* will echo wrong info to display in some cases

With the replacement

* only some control keys are sent
* will not dump garbage to screen/input.

Correct me if I am wrong of course.
The current state is not correct, but it is more functional than if you filter to a specific set of shortcuts.

**Comment by mgazza** [comment]
With the current implementation any shortcut will emit a character shifted by -66, that includes Alt+ Ctrl+ Super+ 

With the replacement implementation only the following is sent when the Ctrl key is pressed. This is consistant with other terminal emulators.

CTRL+SPACE      0
CTRL+@          0
CTRL+A          1
CTRL+B          2
CTRL+C          3
etc...
CTRL+X          24
CTRL+Y          25
CTRL+Z          26
CTRL+[          27
CTRL+\          28
CTRL+]          29
CTRL+^          30
CTRL+_          31

**Comment by mgazza** [comment]
I'm not blocking the usage of Alt/Super. Just interpreting the Ctrl and sending the correct sequences, ignoring out of range keys.
If we find a sequence thats sending the wrong sequence we now have a unit test for it.

**Comment by drunlade** [comment]
The original implementation is incorrect from a usage perspective, regardless of its intended functionality. It renders almost all modifier based inputs unusable, including the common copy/paste shortcuts, alt-key based foreign character inputs, etc.

An example application I tested was borderline unusable due to this broken key handling as pretty much any ctrl/alt/super based input resulted in unintended behaviour, and that's not even touching on how it breaks foreign character input.

> The current state is not correct, but it is more functional than if you filter to a specific set of shortcuts.

So based on what I've tested and experienced, the above statement is not true, functionally the original code breaks almost all usages of ctrl/alt/super inputs, rendering the terminal practically unusable in most applications.

The code in this PR has fixed most (not sure about all yet) the issues I had with non-standard key input.

**Review by andydotxyz — APPROVED** [review]
My apologies, from the diff it was not possible to understand that the change was as described. I am probably trying to review too many things in a short period!

As this is an improvement in the ways that matter let's land it and work to make other improvements later.

**Pull request merged**
